### ISSUE TITLE
ConnectionError exception in event_proxy function

### ISSUE THREAD

**Issue by egorsmkv** [imankulov/django-plausible-proxy#10]
* Django Plausible Proxy version: 0.5.1
* Python version: 3.11.7
* Operating System: Ubuntu

### Description

The code here - https://github.com/imankulov/django-plausible-proxy/blob/fef53201a00c133051fff300516bef2277cfd9ac/plausible_proxy/views.py#L35 - raises ConnectionError:

```
HTTPSConnectionPool(host='plausible.io', port=443): Max retries exceeded with url: /api/event (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f150a4b5b10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

Can we add ability to replace the standard function?

**Comment by imankulov** [comment]
Hey @egorsmkv! Thank you so much for giving django-plausible-proxy a try and sharing your feedback.

Could you please provide more details about what you're trying to achieve and how you envision the developer experience?

For instance, I'm curious to know how replacing a standard function can help prevent ConnectionErrors. Are you looking to suppress these errors so they don't appear in Sentry? Would it be helpful if the view caught ConnectionErrors and returned a 504 error, similar to how requests.Timeout is currently handled?

Looking forward to hearing more from you!

**Comment by egorsmkv** [comment]
I have switched to a local version of Plausible so this issue is not appearing already.

**Comment by itsthejoker** [comment]
I am also receiving this error and have for a long time. I just want it to not show up in my logs; if I could control it myself, I'd just suppress the error.
