### ISSUE TITLE
Change Suggestion -- namespace django urls

### ISSUE THREAD

**Issue by aareman** [imankulov/django-plausible-proxy#2]
Hi @imankulov , thanks for this django plugin.

One suggestion I was thinking about is to namespace the proxy urls, so they aren't at the top level (`/`). This is in case there would be a conflict between another `/js/script.js` etc...

I'm not sure how ad blockers work, so a namespace of "plausible" may get blocked. 

Perhaps `plsbl/js/script.js`

**Comment by imankulov** [comment]
Great suggestion. Thanks for proposing this. Indeed, somehow I didn't notice that `js/script.js` is too generic. I'll address it later today.

**Comment by imankulov** [comment]
Addressed and released in the v0.3.0.
